# Generated by Django 3.2.14 on 2022-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimmerreviewer', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('1', '2000'), ('2', '2001'), ('3', '2002'), ('4', '2003'), ('5', '2004'), ('6', '2005'), ('7', '2006'), ('8', '2007'), ('9', '2008'), ('10', '2009'), ('11', '2010'), ('12', '2011'), ('13', '2012'), ('14', '2013'), ('15', '2014'), ('16', '2015'), ('17', '2016'), ('18', '2017'), ('19', '2018'), ('20', '2019'), ('21', '2020'), ('22', '2021'), ('23', '2022')], default='2000', max_length=10),
        ),
    ]
