# Generated by Django 3.2.14 on 2022-07-10 03:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimmerreviewer', '0006_auto_20220709_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255, verbose_name=django.contrib.auth.models.User),
        ),
    ]
