# Generated by Django 3.2.14 on 2022-07-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimmerreviewer', '0007_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
