# Generated by Django 3.2.14 on 2022-07-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimmerreviewer', '0009_auto_20220710_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1-SERIES', '1-SERIES'), ('3-SERIES', '3-SERIES'), ('5-SERIES', '5-SERIES'), ('OTHER', 'OTHER')], default='OTHER', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Other', 'Other')], default='OTHER', max_length=10),
        ),
    ]
