# Generated by Django 3.2.14 on 2022-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimmerreviewer', '0010_auto_20220712_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
